Repository moonshotcollective/tip.party, pull requests merged in 2021-09, with the labels that each got.

#43 Tip.party Rebranding
  README.md
  packages/react-app/src/components/Header.jsx
  packages/react-app/src/views/Admin.jsx
Labels: branding

#44 Remove burner wallet
  packages/react-app/src/App.jsx
  packages/react-app/src/components/Account.jsx
  packages/react-app/src/hooks/UserSigner.js
Labels: front-end

#48 Issue-30: Rooms and Websocket setup
  packages/react-app/.sample.env
  packages/react-app/package.json
  packages/react-app/src/App.jsx
  packages/react-app/src/views/Room.jsx
  packages/react-app/src/views/index.js
Labels: enhancement, front-end

#46 Update LICENSE
  LICENSE
Labels: branding

#52 Update action scripts for custom routes
  .github/workflows/staging-surge-deploy.yml
  .github/workflows/surge-deploy.yml
Labels: back-end

#49 issue-36: Add Fetch ENS Names Toggle switch
  packages/react-app/package.json
  packages/react-app/src/App.jsx
  packages/react-app/src/views/Admin.jsx
Labels: enhancement, front-end

#51 update for default zero addy usage
  packages/react-app/src/App.jsx
  packages/react-app/src/components/Account.jsx
Labels: bug

#59 issue-57: Remove Payout from Admin Panel
  packages/react-app/src/views/Admin.jsx
  packages/react-app/src/views/Room.jsx
Labels: front-end

#62 Issue 60 - Clean up console warnings
  packages/hardhat/deploy/01_deploy_tokendistributor_contract.js
  packages/react-app/src/App.jsx
  packages/react-app/src/components/Account.jsx
  packages/react-app/src/helpers/Transactor.js
  packages/react-app/src/hooks/ExchangePrice.js
  packages/react-app/src/hooks/GasPrice.js
  packages/react-app/src/hooks/TokenList.js
  packages/react-app/src/hooks/UserSigner.js
  packages/react-app/src/views/ExampleUI.jsx
  packages/react-app/src/views/Hints.jsx
  packages/react-app/src/views/Room.jsx
  packages/react-app/src/views/index.js
Labels: front-end, clean-up

#61 Issue-38: Updated Navbar UI
  packages/hardhat/.sample.env
  packages/hardhat/deploy/01_deploy_tokendistributor_contract.js
  packages/hardhat/package.json
  packages/react-app/public/index.html
  packages/react-app/src/App.jsx
  packages/react-app/src/components/Account.jsx
  packages/react-app/src/components/Address.jsx
  packages/react-app/src/contracts/hardhat_contracts.json
Labels: enhancement, front-end

#74 Added Gas Gauge and Eth sending portal
  packages/react-app/src/App.jsx
  packages/react-app/src/contracts/hardhat_contracts.json
  packages/react-app/src/views/Room.jsx
Labels: Approved

#95 update graph version
  packages/subgraph/package.json
Labels: dependency update

#96 Issue-91: Valid ENS Name Check
  packages/react-app/src/components/Address.jsx
  packages/react-app/src/contracts/hardhat_contracts.json
  packages/react-app/src/views/Room.jsx
Labels: bug

#102 Issue 101: Updated Readme with .env requirements
  README.md
Labels: documentation

#115 Custom ERC20 token import
  packages/react-app/src/components/AddressModal.jsx
  packages/react-app/src/components/index.js
  packages/react-app/src/constants.js
  packages/react-app/src/contracts/hardhat_contracts.json
  packages/react-app/src/hooks/TokenImport.js
  packages/react-app/src/hooks/index.js
  packages/react-app/src/views/Room.jsx
Labels: enhancement
